### ISSUE TITLE
Regards Enhancement in Paging rather then vertical scroll 

### ISSUE THREAD

**Issue by Himanshu4003** [pettarin/epub3reader#21]
Hello ,

I have test you app and i found it very use full to me for my epub 3.0 book ,but only thing i want to known from you is when to move to my book's first chapter .it load one xhtml ,so you have idea how i can  making paging from that xhtml while loading it in WebView.

**Comment by pettarin** [comment]
Please be aware of https://github.com/pettarin/epub3reader#important-notice-2015-07-27
