### ISSUE TITLE
FATAL EXCEPTION: main java.lang.VerifyError

### ISSUE THREAD

**Issue by ratheeshcn** [pettarin/epub3reader#22]
when i import the code in eclipse i got this error .i did every settings in build path. The main java.lang.VerifyError is coming in the line navigator = new EpubNavigator(2, this); in the main activity. Please suggest me what will be the issue

**Comment by ratheeshcn** [comment]
I did and it was build couple of months before. I purchased the skypub libraries and customize it . now the app is working like a charm. thanks for the reply.

**Comment by pettarin** [comment]
Please be aware of https://github.com/pettarin/epub3reader#important-notice-2015-07-27
