### ISSUE TITLE
Not showing the menu!

### ISSUE THREAD

**Issue by RahulSayare** [pettarin/epub3reader#24]
I have downloaded and executed the code. It is opening the books, but the menu option is not showing my emulator. And the reader is not showing end of book. I am using api 16 and android version 4.1.2.
![screenshot](https://cloud.githubusercontent.com/assets/8479116/3951050/65104734-26d0-11e4-8fd8-d75d87233d84.png)

**Comment by pettarin** [comment]
Please be aware of https://github.com/pettarin/epub3reader#important-notice-2015-07-27
