### ISSUE TITLE
Change all memory path to external microsd 

### ISSUE THREAD

**Issue by norani** [pettarin/epub3reader#27]
I want this app to only **use the external microsd** instead of internal storage. So I changed the  path which is `Environment.getExternalStorageDirectory()); ` to `/storage/microsd`  . 

The problem is in EpubManipulator.java, after I changed the 
`
	public static String location = Environment.getExternalStorageDirectory()
			+ "/epubtemp/"; `
to 
`public static String location = "/storage/MicroSD/epubtemp";`
-User click Open Book 1>Select Book>Selected book not opened(it remains the same like no action taken)
`

**Comment by rajvalentino** [comment]
check whether the path you specified "/storage/MicroSD/epubtemp" exist, 
Missing the "/" at suffix may be the problem,
Check with this :  public static String location = "/storage/MicroSD/epubtemp/";

**Comment by norani** [comment]
I checked the path but it not existed, so I manually create a folder named "epubtemp". I put "/" at suffix. But it still not open the selected book. But I think I should not manually create the "epubtemp" folder because it should be auto-created the "epubtemp" through programmatically. Does it relates to write permission for microsd?

**Comment by pettarin** [comment]
Please be aware of https://github.com/pettarin/epub3reader#important-notice-2015-07-27
