### ISSUE TITLE
Error 404, File not found issue for 1 ebook.

### ISSUE THREAD

**Issue by sush4042** [pettarin/epub3reader#28]
I am using the Skyepub.jar in my Android app to display the ebooks(.epub file). most of ebooks from internal memory render and preview fine, where as my one epub file getting error like "Error 404, File not found". I have tested the same epub file from asset with 'SkyTest App'(Tutorial App), It is preview properly but getting error in my application.
Please help on this issue.
Thanks

**Comment by pettarin** [comment]
Please read https://github.com/pettarin/epub3reader#important-notice-2015-07-27 .

Closing.

**Comment by sush4042** [comment]
I am getting following error Logs from system,

 W/System.err: java.io.FileNotFoundException: http://localhost:61001/Domina/META-INF/encryption.xml
 W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
 W/System.err:     at com.skytree.epub.Book.parseEncryption(Unknown Source)
 W/System.err:     at com.skytree.epub.Book.parseXML(Unknown Source)
 W/System.err:     at com.skytree.epub.cx.aW(Unknown Source)
 W/System.err:     at com.skytree.epub.cx.s(Unknown Source)
 W/System.err:     at com.skytree.epub.db.run(Unknown Source)
 W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
 W/System.err:     at android.os.Looper.loop(Looper.java:194)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5534)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by pettarin** [comment]
You need to report the error to the developer of Skyepub.jar .

This project (eput3reader) has nothing to do with what you are using, AND as said in the link I posted above, this project is no longer being developed.

Thank you.
